import "./globals.css";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import localFont from "next/font/local";

const Graphik = localFont({
  src: "./fonts/Graphik-Regular.woff2",
  variable: "--font-graphik",
});

const FinancierDisplay = localFont({
  src: "./fonts/FinancierDisplay-Regular.woff2",
  variable: "--font-financier",
});

export const metadata: Metadata = {
  title: "LifeShare - Blood Donation & Emergency Services Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        Graphik.variable,
        FinancierDisplay.variable,
      )}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
