import "./globals.css";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import localFont from "next/font/local";

const Graphik = localFont({
  src: [
    {
      path: "./fonts/Graphik-Regular.woff2",
      weight: "400",
      style: "normal",
    }
  ],
  variable: "--font-graphik",
});

const FinancierDisplay = localFont({
  src: [
    {
      path: "./fonts/FinancierDisplay-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/FinancierDisplay-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/FinancierDisplay-LightItalic.woff2",
      weight: "300",
      style: "italic",
    },
  ],
  variable: "--font-financier",
});

export const metadata: Metadata = {
  title: "LifeShare - Blood Donation & Emergency Services Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        Graphik.variable,
        FinancierDisplay.variable, // Both variables smoothly injected here
      )}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
